### ISSUE TITLE
Todo.

### ISSUE THREAD

**Issue by nickfang** [nickfang/personal-dashboard#1]
weather
- [x] Get today's weather
- [x] Get past 3 days weather
- [ ] Switch between imperial and metric
- [ ] Create view for today and past weather
- [x] Create table for showing hourly barometric pressure

Stocks
- [ ] find api for getting stock values

News
- [ ] find api for news
